"""Add phone columns to users and restaurants

Revision ID: 16dfd0e619b1
Revises: 6292170660f8
Create Date: 2025-03-26 07:55:33.260043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dfd0e619b1'
down_revision: Union[str, None] = '6292170660f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column(
        'phone', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('restaurants', 'phone')
    # ### end Alembic commands ###
