"""Add restaurant_id to users

Revision ID: 6292170660f8
Revises: ba50ff0e4e38
Create Date: 2025-03-25 17:13:51.448810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6292170660f8'
down_revision: Union[str, None] = 'ba50ff0e4e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restaurant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'restaurant_id')
    # ### end Alembic commands ###
