"""Creation of restaurants table

Revision ID: 7b22624af1e1
Revises: f7ad928581a9
Create Date: 2025-03-25 15:40:37.411408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b22624af1e1'
down_revision: Union[str, None] = 'f7ad928581a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('restaurant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'restaurant_id')
    # ### end Alembic commands ###
